# Generated by Django 4.2.24 on 2025-09-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_sliderimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='Products/'),
        ),
    ]
